title: Milton Keynes Chess Club
email: webmasters@miltonkeyneschessclub.co.uk
description: >-
  Milton Keynes Chess Club is the home of adult over the board chess in Milton
  Keynes and the surrounding area. We compete in the bedfordshire league, hold
  internal competitions and play casual chess every thursday.
baseurl: ""
url: ""

twitter_username: miltonkeyneschessclub
github_username:  miltonkeyneschessclub

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages
  - _posts

minimal_mistakes_skin: "mkchess" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
