title: Milton Keynes Chess Club
email: webmaster@miltonkeyneschessclub.co.uk
description: >-
  Milton Keynes Chess Club is the home of adult over the board chess in Milton
  Keynes and the surrounding area. We compete in the bedfordshire league, hold
  internal competitions and play casual chess every thursday.
baseurl: ""
url: ""

twitter_username: miltonkeyneschessclub
github_username:  miltonkeyneschessclub

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-email-protect

include:
  - _pages
  - _posts

minimal_mistakes_skin: "mkchess" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

exclude:
  - _build
  - .github

analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-38KQRT08VQ"
    anonymize_ip         : true

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/people/Milton-Keynes-Chess-Club/61567743985942/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiltonKeynesChessClub"

# Markdown Processing
kramdown:
  auto_ids: true
  toc_levels: 2..6

# Front matter defaults
breadcrumbs: true
defaults:
  - scope:
      path: "_pages/results"
    values:
      sidebar:
        nav: results
  - scope:
      path: "_pages/about"
    values:
      sidebar:
        nav: about
  - scope:
      path: "_pages/about/members"
    values:
      toc: true
      toc_sticky: true
      sidebar:
        nav: about
  - scope:
      type: posts
    values:
      layout: single
      permalink: /posts/:categories/:year-:month-:day-:title:output_ext
      show_date: true
      related: true
      author_profile: false
      read_time: false
      sidebar:
        nav: posts
