title: Milton Keynes Chess Club
email: webmasters@mkchessclub.co.uk
description: >-
  Milton Keynes Chess Club is the home of adult over the board chess in Milton
  Keynes and the surrounding area. We compete in the bedfordshire league, hold
  internal competitions and play casual chess every thursday.
baseurl: ""
url: ""

twitter_username: miltonkeyneschessclub
github_username:  miltonkeyneschessclub

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-email-protect

include:
  - _pages
  - _posts

minimal_mistakes_skin: "mkchess" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

exclude:
  - _build
  - .github


analytics:
  provider               : "google"
  google:
    tracking_id          : "G-38KQRT08VQ"
    anonymize_ip         : true

# Markdown Processing
kramdown:
  auto_ids: true
  toc_levels: 2..6

# Front matter defaults
defaults:
  - scope:
      path: "_pages/teams"
    values:
      sidebar:
        nav: results
  - scope:
      path: "_pages/posts"
    values:
      sidebar:
        nav: posts
  - scope:
      path: "_pages/about"
    values:
      sidebar:
        nav: about
      breadcrumbs: true
  - scope:
      path: "_pages/about/members"
    values:
      sidebar:
        nav: about
      toc: true
      toc_sticky: true
  - scope:
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      related: true
