#!/usr/bin/env ruby
require "csv"
require "yaml"

matches_path = ARGV[0] or abort "usage: build_bcl_player_stats.rb MATCHES_YAML MEMBERS_CSV OUT_YAML"
members_path = ARGV[1] or abort "usage: build_bcl_player_stats.rb MATCHES_YAML MEMBERS_CSV OUT_YAML"
out_path = ARGV[2] or abort "usage: build_bcl_player_stats.rb MATCHES_YAML MEMBERS_CSV OUT_YAML"

matches = YAML.load_file( matches_path )
members_by_ecf = {}
CSV.foreach( members_path, headers: true ) do | row |
	ecf = row[ "ecfname" ]&.strip
	next if ecf.nil? || ecf.empty?

	members_by_ecf[ ecf ] = row[ "slug" ]
end

def parse_outcome( result_str )
	s = result_str.to_s.strip
	return :draw if s.include?( "\u00BD" )

	return nil unless s =~ /^(.+?)\s*-\s*(.+)$/

	left = normalize_score_part( Regexp.last_match( 1 ) )
	right = normalize_score_part( Regexp.last_match( 2 ) )
	return nil if left.nil? || right.nil?

	return :draw if ( left - right ).abs < 1e-9

	left > right ? :home_win : :away_win
end

def normalize_score_part( part )
	part = part.strip
	return 0.5 if part == "\u00BD" || part =~ /^0\.5$/i || part =~ /^1\/2$/i

	Float( part )
rescue ArgumentError
	nil
end

def opponent_rating_for_best( raw )
	n = raw.is_a?( Integer ) ? raw : raw.to_s.to_i

	n.positive? ? n : nil
end

stats = {}

matches.each do | division, games |
	next unless games.is_a?( Array )

	games.each do | g |
		outcome = parse_outcome( g[ "result" ] )
		next if outcome.nil?

		home = g[ "home" ]
		away = g[ "away" ]
		next unless home.is_a?( Hash ) && away.is_a?( Hash )

		[
			[ home, away, :home ],
			[ away, home, :away ]
		].each do | player_side, opp_side, role |
			name = player_side[ "name" ]
			team = player_side[ "team" ]
			next if name.nil? || team.nil?

			slug = members_by_ecf[ name ]
			next if slug.nil?

			stats[ division ] ||= {}
			stats[ division ][ team ] ||= {}
			row = stats[ division ][ team ][ slug ] ||= {
				"played" => 0,
				"won" => 0,
				"lost" => 0,
				"drawn" => 0,
				"best_win_opponent_rating" => nil
			}

			row[ "played" ] += 1

			won = ( role == :home && outcome == :home_win ) || ( role == :away && outcome == :away_win )
			lost = ( role == :home && outcome == :away_win ) || ( role == :away && outcome == :home_win )

			if won
				row[ "won" ] += 1
				orating = opponent_rating_for_best( opp_side[ "rating" ] )
				if orating
					cur = row[ "best_win_opponent_rating" ]
					row[ "best_win_opponent_rating" ] = cur ? [ cur, orating ].max : orating
				end
			elsif lost
				row[ "lost" ] += 1
			elsif outcome == :draw
				row[ "drawn" ] += 1
			end
		end
	end
end

out = {}
stats.keys.sort.each do | div |
	out[ div ] = {}
	stats[ div ].keys.sort.each do | team |
		slug_map = {}
		stats[ div ][ team ].keys.sort.each do | slug |
			rec = stats[ div ][ team ][ slug ].dup
			rec.delete( "best_win_opponent_rating" ) if rec[ "best_win_opponent_rating" ].nil?
			slug_map[ slug ] = rec
		end
		out[ div ][ team ] = slug_map
	end
end

header = "# File generated by importBCLData.sh script. Do not modify.\n"
File.write( out_path, header + YAML.dump( out ).sub( /\A---\n/, "" ) )
