name: Import results
on:
  schedule:
    - cron: "33 1,7,13,19 * * *" # at 33m past the hour, four times a day
jobs:
  importresults:
    name: Import results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run import
        working-directory: ./_build/scripts
        run: |
          ./importBCLData.sh
          ./importInternalCompetitions.sh

      - name: Push new results back to github
        run: |
          changes=$( git diff )
          if [[ -z $changes ]] ; then
            echo "No changes detected, nothing to do."
            exit;
          fi
          git config --global user.name 'mk-chess-club'
          git config --global user.email 'miltonkeyneschessclub@gmail.com'
          git commit -am "Latest import from the ECF LMS for bedfordhire chess results"
          git push